type TargetResult = 'hit' | 'missed' | null;

interface Turn {
  targetResult: TargetResult;
  timestamp?: number; // Generated by Sender (target sensor), used for calculation and result display
}

type GameRounds = Turns[];

// LoRa related stuff
interface ILoRaMessage {
  systemId: string;
  type: string;
  meta: {
    orginator: string;
  }
}

interface ITargetHitMessage extends ILoRaMessage {
  payload: {
    targetId: string;
    timestamp: string;
  }
}

