/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as TestIndexImport } from './routes/test/index';
import { Route as ManageIndexImport } from './routes/manage/index';
import { Route as DashboardIndexImport } from './routes/dashboard/index';
import { Route as BigScreenIndexImport } from './routes/big-screen/index';
import { Route as ManageUsersIndexImport } from './routes/manage/users/index';
import { Route as ManageStagesIndexImport } from './routes/manage/stages/index';
import { Route as ManageDevicesIndexImport } from './routes/manage/devices/index';
import { Route as ManageStagesCurrentImport } from './routes/manage/stages/current';
import { Route as ManageStagesStageIdImport } from './routes/manage/stages/$stageId';
import { Route as ManageDevicesDeviceIdImport } from './routes/manage/devices/$deviceId';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const TestIndexRoute = TestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any);

const ManageIndexRoute = ManageIndexImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRoute,
} as any);

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any);

const BigScreenIndexRoute = BigScreenIndexImport.update({
  id: '/big-screen/',
  path: '/big-screen/',
  getParentRoute: () => rootRoute,
} as any);

const ManageUsersIndexRoute = ManageUsersIndexImport.update({
  id: '/manage/users/',
  path: '/manage/users/',
  getParentRoute: () => rootRoute,
} as any);

const ManageStagesIndexRoute = ManageStagesIndexImport.update({
  id: '/manage/stages/',
  path: '/manage/stages/',
  getParentRoute: () => rootRoute,
} as any);

const ManageDevicesIndexRoute = ManageDevicesIndexImport.update({
  id: '/manage/devices/',
  path: '/manage/devices/',
  getParentRoute: () => rootRoute,
} as any);

const ManageStagesCurrentRoute = ManageStagesCurrentImport.update({
  id: '/manage/stages/current',
  path: '/manage/stages/current',
  getParentRoute: () => rootRoute,
} as any);

const ManageStagesStageIdRoute = ManageStagesStageIdImport.update({
  id: '/manage/stages/$stageId',
  path: '/manage/stages/$stageId',
  getParentRoute: () => rootRoute,
} as any);

const ManageDevicesDeviceIdRoute = ManageDevicesDeviceIdImport.update({
  id: '/manage/devices/$deviceId',
  path: '/manage/devices/$deviceId',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/big-screen/': {
      id: '/big-screen/';
      path: '/big-screen';
      fullPath: '/big-screen';
      preLoaderRoute: typeof BigScreenIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/manage/': {
      id: '/manage/';
      path: '/manage';
      fullPath: '/manage';
      preLoaderRoute: typeof ManageIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/test/': {
      id: '/test/';
      path: '/test';
      fullPath: '/test';
      preLoaderRoute: typeof TestIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/manage/devices/$deviceId': {
      id: '/manage/devices/$deviceId';
      path: '/manage/devices/$deviceId';
      fullPath: '/manage/devices/$deviceId';
      preLoaderRoute: typeof ManageDevicesDeviceIdImport;
      parentRoute: typeof rootRoute;
    };
    '/manage/stages/$stageId': {
      id: '/manage/stages/$stageId';
      path: '/manage/stages/$stageId';
      fullPath: '/manage/stages/$stageId';
      preLoaderRoute: typeof ManageStagesStageIdImport;
      parentRoute: typeof rootRoute;
    };
    '/manage/stages/current': {
      id: '/manage/stages/current';
      path: '/manage/stages/current';
      fullPath: '/manage/stages/current';
      preLoaderRoute: typeof ManageStagesCurrentImport;
      parentRoute: typeof rootRoute;
    };
    '/manage/devices/': {
      id: '/manage/devices/';
      path: '/manage/devices';
      fullPath: '/manage/devices';
      preLoaderRoute: typeof ManageDevicesIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/manage/stages/': {
      id: '/manage/stages/';
      path: '/manage/stages';
      fullPath: '/manage/stages';
      preLoaderRoute: typeof ManageStagesIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/manage/users/': {
      id: '/manage/users/';
      path: '/manage/users';
      fullPath: '/manage/users';
      preLoaderRoute: typeof ManageUsersIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/big-screen': typeof BigScreenIndexRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/manage': typeof ManageIndexRoute;
  '/test': typeof TestIndexRoute;
  '/manage/devices/$deviceId': typeof ManageDevicesDeviceIdRoute;
  '/manage/stages/$stageId': typeof ManageStagesStageIdRoute;
  '/manage/stages/current': typeof ManageStagesCurrentRoute;
  '/manage/devices': typeof ManageDevicesIndexRoute;
  '/manage/stages': typeof ManageStagesIndexRoute;
  '/manage/users': typeof ManageUsersIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/big-screen': typeof BigScreenIndexRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/manage': typeof ManageIndexRoute;
  '/test': typeof TestIndexRoute;
  '/manage/devices/$deviceId': typeof ManageDevicesDeviceIdRoute;
  '/manage/stages/$stageId': typeof ManageStagesStageIdRoute;
  '/manage/stages/current': typeof ManageStagesCurrentRoute;
  '/manage/devices': typeof ManageDevicesIndexRoute;
  '/manage/stages': typeof ManageStagesIndexRoute;
  '/manage/users': typeof ManageUsersIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/big-screen/': typeof BigScreenIndexRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/manage/': typeof ManageIndexRoute;
  '/test/': typeof TestIndexRoute;
  '/manage/devices/$deviceId': typeof ManageDevicesDeviceIdRoute;
  '/manage/stages/$stageId': typeof ManageStagesStageIdRoute;
  '/manage/stages/current': typeof ManageStagesCurrentRoute;
  '/manage/devices/': typeof ManageDevicesIndexRoute;
  '/manage/stages/': typeof ManageStagesIndexRoute;
  '/manage/users/': typeof ManageUsersIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/big-screen'
    | '/dashboard'
    | '/manage'
    | '/test'
    | '/manage/devices/$deviceId'
    | '/manage/stages/$stageId'
    | '/manage/stages/current'
    | '/manage/devices'
    | '/manage/stages'
    | '/manage/users';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/big-screen'
    | '/dashboard'
    | '/manage'
    | '/test'
    | '/manage/devices/$deviceId'
    | '/manage/stages/$stageId'
    | '/manage/stages/current'
    | '/manage/devices'
    | '/manage/stages'
    | '/manage/users';
  id:
    | '__root__'
    | '/'
    | '/big-screen/'
    | '/dashboard/'
    | '/manage/'
    | '/test/'
    | '/manage/devices/$deviceId'
    | '/manage/stages/$stageId'
    | '/manage/stages/current'
    | '/manage/devices/'
    | '/manage/stages/'
    | '/manage/users/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BigScreenIndexRoute: typeof BigScreenIndexRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  ManageIndexRoute: typeof ManageIndexRoute;
  TestIndexRoute: typeof TestIndexRoute;
  ManageDevicesDeviceIdRoute: typeof ManageDevicesDeviceIdRoute;
  ManageStagesStageIdRoute: typeof ManageStagesStageIdRoute;
  ManageStagesCurrentRoute: typeof ManageStagesCurrentRoute;
  ManageDevicesIndexRoute: typeof ManageDevicesIndexRoute;
  ManageStagesIndexRoute: typeof ManageStagesIndexRoute;
  ManageUsersIndexRoute: typeof ManageUsersIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BigScreenIndexRoute: BigScreenIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ManageIndexRoute: ManageIndexRoute,
  TestIndexRoute: TestIndexRoute,
  ManageDevicesDeviceIdRoute: ManageDevicesDeviceIdRoute,
  ManageStagesStageIdRoute: ManageStagesStageIdRoute,
  ManageStagesCurrentRoute: ManageStagesCurrentRoute,
  ManageDevicesIndexRoute: ManageDevicesIndexRoute,
  ManageStagesIndexRoute: ManageStagesIndexRoute,
  ManageUsersIndexRoute: ManageUsersIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/big-screen/",
        "/dashboard/",
        "/manage/",
        "/test/",
        "/manage/devices/$deviceId",
        "/manage/stages/$stageId",
        "/manage/stages/current",
        "/manage/devices/",
        "/manage/stages/",
        "/manage/users/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/big-screen/": {
      "filePath": "big-screen/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/manage/": {
      "filePath": "manage/index.tsx"
    },
    "/test/": {
      "filePath": "test/index.tsx"
    },
    "/manage/devices/$deviceId": {
      "filePath": "manage/devices/$deviceId.tsx"
    },
    "/manage/stages/$stageId": {
      "filePath": "manage/stages/$stageId.tsx"
    },
    "/manage/stages/current": {
      "filePath": "manage/stages/current.tsx"
    },
    "/manage/devices/": {
      "filePath": "manage/devices/index.tsx"
    },
    "/manage/stages/": {
      "filePath": "manage/stages/index.tsx"
    },
    "/manage/users/": {
      "filePath": "manage/users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
