/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as BigScreenRouteImport } from './routes/big-screen';
import { Route as IndexRouteImport } from './routes/index';
import { Route as UsersIndexRouteImport } from './routes/users/index';
import { Route as TestIndexRouteImport } from './routes/test/index';
import { Route as StagesIndexRouteImport } from './routes/stages/index';
import { Route as DevicesIndexRouteImport } from './routes/devices/index';
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index';
import { Route as StagesCurrentRouteImport } from './routes/stages/current';
import { Route as StagesStageIdRouteImport } from './routes/stages/$stageId';
import { Route as DevicesDeviceIdRouteImport } from './routes/devices/$deviceId';

const BigScreenRoute = BigScreenRouteImport.update({
  id: '/big-screen',
  path: '/big-screen',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any);
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any);
const StagesIndexRoute = StagesIndexRouteImport.update({
  id: '/stages/',
  path: '/stages/',
  getParentRoute: () => rootRouteImport,
} as any);
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any);
const StagesCurrentRoute = StagesCurrentRouteImport.update({
  id: '/stages/current',
  path: '/stages/current',
  getParentRoute: () => rootRouteImport,
} as any);
const StagesStageIdRoute = StagesStageIdRouteImport.update({
  id: '/stages/$stageId',
  path: '/stages/$stageId',
  getParentRoute: () => rootRouteImport,
} as any);
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/big-screen': typeof BigScreenRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/stages/$stageId': typeof StagesStageIdRoute;
  '/stages/current': typeof StagesCurrentRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/devices': typeof DevicesIndexRoute;
  '/stages': typeof StagesIndexRoute;
  '/test': typeof TestIndexRoute;
  '/users': typeof UsersIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/big-screen': typeof BigScreenRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/stages/$stageId': typeof StagesStageIdRoute;
  '/stages/current': typeof StagesCurrentRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/devices': typeof DevicesIndexRoute;
  '/stages': typeof StagesIndexRoute;
  '/test': typeof TestIndexRoute;
  '/users': typeof UsersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/big-screen': typeof BigScreenRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/stages/$stageId': typeof StagesStageIdRoute;
  '/stages/current': typeof StagesCurrentRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/devices/': typeof DevicesIndexRoute;
  '/stages/': typeof StagesIndexRoute;
  '/test/': typeof TestIndexRoute;
  '/users/': typeof UsersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/big-screen'
    | '/devices/$deviceId'
    | '/stages/$stageId'
    | '/stages/current'
    | '/dashboard'
    | '/devices'
    | '/stages'
    | '/test'
    | '/users';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/big-screen'
    | '/devices/$deviceId'
    | '/stages/$stageId'
    | '/stages/current'
    | '/dashboard'
    | '/devices'
    | '/stages'
    | '/test'
    | '/users';
  id:
    | '__root__'
    | '/'
    | '/big-screen'
    | '/devices/$deviceId'
    | '/stages/$stageId'
    | '/stages/current'
    | '/dashboard/'
    | '/devices/'
    | '/stages/'
    | '/test/'
    | '/users/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BigScreenRoute: typeof BigScreenRoute;
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRoute;
  StagesStageIdRoute: typeof StagesStageIdRoute;
  StagesCurrentRoute: typeof StagesCurrentRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DevicesIndexRoute: typeof DevicesIndexRoute;
  StagesIndexRoute: typeof StagesIndexRoute;
  TestIndexRoute: typeof TestIndexRoute;
  UsersIndexRoute: typeof UsersIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/big-screen': {
      id: '/big-screen';
      path: '/big-screen';
      fullPath: '/big-screen';
      preLoaderRoute: typeof BigScreenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/users/': {
      id: '/users/';
      path: '/users';
      fullPath: '/users';
      preLoaderRoute: typeof UsersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/test/': {
      id: '/test/';
      path: '/test';
      fullPath: '/test';
      preLoaderRoute: typeof TestIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/stages/': {
      id: '/stages/';
      path: '/stages';
      fullPath: '/stages';
      preLoaderRoute: typeof StagesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/devices/': {
      id: '/devices/';
      path: '/devices';
      fullPath: '/devices';
      preLoaderRoute: typeof DevicesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/stages/current': {
      id: '/stages/current';
      path: '/stages/current';
      fullPath: '/stages/current';
      preLoaderRoute: typeof StagesCurrentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/stages/$stageId': {
      id: '/stages/$stageId';
      path: '/stages/$stageId';
      fullPath: '/stages/$stageId';
      preLoaderRoute: typeof StagesStageIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/devices/$deviceId': {
      id: '/devices/$deviceId';
      path: '/devices/$deviceId';
      fullPath: '/devices/$deviceId';
      preLoaderRoute: typeof DevicesDeviceIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BigScreenRoute: BigScreenRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRoute,
  StagesStageIdRoute: StagesStageIdRoute,
  StagesCurrentRoute: StagesCurrentRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DevicesIndexRoute: DevicesIndexRoute,
  StagesIndexRoute: StagesIndexRoute,
  TestIndexRoute: TestIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
