/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as UsersIndexImport } from './routes/users/index';
import { Route as TestIndexImport } from './routes/test/index';
import { Route as StagesIndexImport } from './routes/stages/index';
import { Route as DevicesIndexImport } from './routes/devices/index';
import { Route as DashboardIndexImport } from './routes/dashboard/index';
import { Route as StagesCurrentImport } from './routes/stages/current';
import { Route as StagesStageIdImport } from './routes/stages/$stageId';
import { Route as DevicesDeviceIdImport } from './routes/devices/$deviceId';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any);

const TestIndexRoute = TestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any);

const StagesIndexRoute = StagesIndexImport.update({
  id: '/stages/',
  path: '/stages/',
  getParentRoute: () => rootRoute,
} as any);

const DevicesIndexRoute = DevicesIndexImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => rootRoute,
} as any);

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any);

const StagesCurrentRoute = StagesCurrentImport.update({
  id: '/stages/current',
  path: '/stages/current',
  getParentRoute: () => rootRoute,
} as any);

const StagesStageIdRoute = StagesStageIdImport.update({
  id: '/stages/$stageId',
  path: '/stages/$stageId',
  getParentRoute: () => rootRoute,
} as any);

const DevicesDeviceIdRoute = DevicesDeviceIdImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/devices/$deviceId': {
      id: '/devices/$deviceId';
      path: '/devices/$deviceId';
      fullPath: '/devices/$deviceId';
      preLoaderRoute: typeof DevicesDeviceIdImport;
      parentRoute: typeof rootRoute;
    };
    '/stages/$stageId': {
      id: '/stages/$stageId';
      path: '/stages/$stageId';
      fullPath: '/stages/$stageId';
      preLoaderRoute: typeof StagesStageIdImport;
      parentRoute: typeof rootRoute;
    };
    '/stages/current': {
      id: '/stages/current';
      path: '/stages/current';
      fullPath: '/stages/current';
      preLoaderRoute: typeof StagesCurrentImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/devices/': {
      id: '/devices/';
      path: '/devices';
      fullPath: '/devices';
      preLoaderRoute: typeof DevicesIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/stages/': {
      id: '/stages/';
      path: '/stages';
      fullPath: '/stages';
      preLoaderRoute: typeof StagesIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/test/': {
      id: '/test/';
      path: '/test';
      fullPath: '/test';
      preLoaderRoute: typeof TestIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/users/': {
      id: '/users/';
      path: '/users';
      fullPath: '/users';
      preLoaderRoute: typeof UsersIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/stages/$stageId': typeof StagesStageIdRoute;
  '/stages/current': typeof StagesCurrentRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/devices': typeof DevicesIndexRoute;
  '/stages': typeof StagesIndexRoute;
  '/test': typeof TestIndexRoute;
  '/users': typeof UsersIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/stages/$stageId': typeof StagesStageIdRoute;
  '/stages/current': typeof StagesCurrentRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/devices': typeof DevicesIndexRoute;
  '/stages': typeof StagesIndexRoute;
  '/test': typeof TestIndexRoute;
  '/users': typeof UsersIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/stages/$stageId': typeof StagesStageIdRoute;
  '/stages/current': typeof StagesCurrentRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/devices/': typeof DevicesIndexRoute;
  '/stages/': typeof StagesIndexRoute;
  '/test/': typeof TestIndexRoute;
  '/users/': typeof UsersIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/devices/$deviceId'
    | '/stages/$stageId'
    | '/stages/current'
    | '/dashboard'
    | '/devices'
    | '/stages'
    | '/test'
    | '/users';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/devices/$deviceId'
    | '/stages/$stageId'
    | '/stages/current'
    | '/dashboard'
    | '/devices'
    | '/stages'
    | '/test'
    | '/users';
  id:
    | '__root__'
    | '/'
    | '/devices/$deviceId'
    | '/stages/$stageId'
    | '/stages/current'
    | '/dashboard/'
    | '/devices/'
    | '/stages/'
    | '/test/'
    | '/users/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRoute;
  StagesStageIdRoute: typeof StagesStageIdRoute;
  StagesCurrentRoute: typeof StagesCurrentRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DevicesIndexRoute: typeof DevicesIndexRoute;
  StagesIndexRoute: typeof StagesIndexRoute;
  TestIndexRoute: typeof TestIndexRoute;
  UsersIndexRoute: typeof UsersIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRoute,
  StagesStageIdRoute: StagesStageIdRoute,
  StagesCurrentRoute: StagesCurrentRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DevicesIndexRoute: DevicesIndexRoute,
  StagesIndexRoute: StagesIndexRoute,
  TestIndexRoute: TestIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/devices/$deviceId",
        "/stages/$stageId",
        "/stages/current",
        "/dashboard/",
        "/devices/",
        "/stages/",
        "/test/",
        "/users/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/devices/$deviceId": {
      "filePath": "devices/$deviceId.tsx"
    },
    "/stages/$stageId": {
      "filePath": "stages/$stageId.tsx"
    },
    "/stages/current": {
      "filePath": "stages/current.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/devices/": {
      "filePath": "devices/index.tsx"
    },
    "/stages/": {
      "filePath": "stages/index.tsx"
    },
    "/test/": {
      "filePath": "test/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
