#ifndef AT_ACTIONS
#define AT_ACTIONS

// Shared with pwa_app
#define ACTION_SETTINGS_GET "SETTINGS/GET"
#define ACTION_SETTINGS_SET "SETTINGS/SET"
#define ACTIONS_DEVICE_ADDED "DEVICE/ADDED"
#define ACTIONS_DEVICE_UPDATED "DEVICE/UPDATED"
#define ACTIONS_DEVICE_REMOVED "DEVICE/REMOVED"
#define ACTIONS_DEVICE_OFFLINE "DEVICE/OFFLINE"
#define ACTIONS_DEVICE_ONLINE "DEVICE/ONLINE"
#define ACTIONS_DEVICE_TARGET_HIT "DEVICE/HIT"
#define ACTION_DEVICE_NOSHOOT_HIT "DEVICE/NOSHOOT_HIT"
#define ACTION_DEVICE_STOP_PLATE "DEVICE/STOP_PLATE_HIT"
#define ACTION_DEVICE_TRIGGERED "DEVICE/TRIGGERED"

#endif