#ifndef AT_ACTION_TYPES
#define AT_ACTION_TYPES

// Shared with pwa_app
#define SETTINGS_GET "SETTINGS/GET"
#define SETTINGS_SET "SETTINGS/SET"
#define DEVICE_ADDED "DEVICE/ADDED"
#define DEVICE_UPDATED "DEVICE/UPDATED"
#define DEVICE_REMOVED "DEVICE/REMOVED"
#define DEVICE_OFFLINE "DEVICE/OFFLINE"
#define DEVICE_ONLINE "DEVICE/ONLINE"
#define SENSOR_TRIGGERED "SENSOR/TRIGGERED"
#endif