#ifndef AT_ACTIONS
#define AT_ACTIONS

// Shared with pwa_app
#define ACTION_SETTINGS_GET "SETTINGS/GET"
#define ACTION_SETTINGS_SET "SETTINGS/SET"
#define ACTIONS_DEVICE_ADDED "DEVICE/ADDED"
#define ACTIONS_DEVICE_UPDATED "DEVICE/UPDATED"
#define ACTIONS_DEVICE_REMOVED "DEVICE/REMOVED"
#define ACTIONS_DEVICE_OFFLINE "DEVICE/OFFLINE"
#define ACTIONS_DEVICE_ONLINE "DEVICE/ONLINE"
#define SENSOR_TRIGGERED "SENSOR/TRIGGERED"
#endif