/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as UsersImport } from './routes/users';
import { Route as ScoresheetImport } from './routes/scoresheet';
import { Route as MatchesImport } from './routes/matches';
import { Route as DevicesImport } from './routes/devices';
import { Route as DashboardImport } from './routes/dashboard';
import { Route as IndexImport } from './routes/index';
import { Route as TestIndexImport } from './routes/test/index';
import { Route as ScoresheetIndexImport } from './routes/scoresheet.index';
import { Route as DevicesIndexImport } from './routes/devices.index';
import { Route as DevicesDeviceIdImport } from './routes/devices.$deviceId';

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any);

const ScoresheetRoute = ScoresheetImport.update({
  id: '/scoresheet',
  path: '/scoresheet',
  getParentRoute: () => rootRoute,
} as any);

const MatchesRoute = MatchesImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRoute,
} as any);

const DevicesRoute = DevicesImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRoute,
} as any);

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const TestIndexRoute = TestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any);

const ScoresheetIndexRoute = ScoresheetIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoresheetRoute,
} as any);

const DevicesIndexRoute = DevicesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesRoute,
} as any);

const DevicesDeviceIdRoute = DevicesDeviceIdImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => DevicesRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    '/devices': {
      id: '/devices';
      path: '/devices';
      fullPath: '/devices';
      preLoaderRoute: typeof DevicesImport;
      parentRoute: typeof rootRoute;
    };
    '/matches': {
      id: '/matches';
      path: '/matches';
      fullPath: '/matches';
      preLoaderRoute: typeof MatchesImport;
      parentRoute: typeof rootRoute;
    };
    '/scoresheet': {
      id: '/scoresheet';
      path: '/scoresheet';
      fullPath: '/scoresheet';
      preLoaderRoute: typeof ScoresheetImport;
      parentRoute: typeof rootRoute;
    };
    '/users': {
      id: '/users';
      path: '/users';
      fullPath: '/users';
      preLoaderRoute: typeof UsersImport;
      parentRoute: typeof rootRoute;
    };
    '/devices/$deviceId': {
      id: '/devices/$deviceId';
      path: '/$deviceId';
      fullPath: '/devices/$deviceId';
      preLoaderRoute: typeof DevicesDeviceIdImport;
      parentRoute: typeof DevicesImport;
    };
    '/devices/': {
      id: '/devices/';
      path: '/';
      fullPath: '/devices/';
      preLoaderRoute: typeof DevicesIndexImport;
      parentRoute: typeof DevicesImport;
    };
    '/scoresheet/': {
      id: '/scoresheet/';
      path: '/';
      fullPath: '/scoresheet/';
      preLoaderRoute: typeof ScoresheetIndexImport;
      parentRoute: typeof ScoresheetImport;
    };
    '/test/': {
      id: '/test/';
      path: '/test';
      fullPath: '/test';
      preLoaderRoute: typeof TestIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

interface DevicesRouteChildren {
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRoute;
  DevicesIndexRoute: typeof DevicesIndexRoute;
}

const DevicesRouteChildren: DevicesRouteChildren = {
  DevicesDeviceIdRoute: DevicesDeviceIdRoute,
  DevicesIndexRoute: DevicesIndexRoute,
};

const DevicesRouteWithChildren =
  DevicesRoute._addFileChildren(DevicesRouteChildren);

interface ScoresheetRouteChildren {
  ScoresheetIndexRoute: typeof ScoresheetIndexRoute;
}

const ScoresheetRouteChildren: ScoresheetRouteChildren = {
  ScoresheetIndexRoute: ScoresheetIndexRoute,
};

const ScoresheetRouteWithChildren = ScoresheetRoute._addFileChildren(
  ScoresheetRouteChildren,
);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRoute;
  '/devices': typeof DevicesRouteWithChildren;
  '/matches': typeof MatchesRoute;
  '/scoresheet': typeof ScoresheetRouteWithChildren;
  '/users': typeof UsersRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/devices/': typeof DevicesIndexRoute;
  '/scoresheet/': typeof ScoresheetIndexRoute;
  '/test': typeof TestIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRoute;
  '/matches': typeof MatchesRoute;
  '/users': typeof UsersRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/devices': typeof DevicesIndexRoute;
  '/scoresheet': typeof ScoresheetIndexRoute;
  '/test': typeof TestIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRoute;
  '/devices': typeof DevicesRouteWithChildren;
  '/matches': typeof MatchesRoute;
  '/scoresheet': typeof ScoresheetRouteWithChildren;
  '/users': typeof UsersRoute;
  '/devices/$deviceId': typeof DevicesDeviceIdRoute;
  '/devices/': typeof DevicesIndexRoute;
  '/scoresheet/': typeof ScoresheetIndexRoute;
  '/test/': typeof TestIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/dashboard'
    | '/devices'
    | '/matches'
    | '/scoresheet'
    | '/users'
    | '/devices/$deviceId'
    | '/devices/'
    | '/scoresheet/'
    | '/test';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/dashboard'
    | '/matches'
    | '/users'
    | '/devices/$deviceId'
    | '/devices'
    | '/scoresheet'
    | '/test';
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/devices'
    | '/matches'
    | '/scoresheet'
    | '/users'
    | '/devices/$deviceId'
    | '/devices/'
    | '/scoresheet/'
    | '/test/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  DevicesRoute: typeof DevicesRouteWithChildren;
  MatchesRoute: typeof MatchesRoute;
  ScoresheetRoute: typeof ScoresheetRouteWithChildren;
  UsersRoute: typeof UsersRoute;
  TestIndexRoute: typeof TestIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRouteWithChildren,
  MatchesRoute: MatchesRoute,
  ScoresheetRoute: ScoresheetRouteWithChildren,
  UsersRoute: UsersRoute,
  TestIndexRoute: TestIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/devices",
        "/matches",
        "/scoresheet",
        "/users",
        "/test/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/devices": {
      "filePath": "devices.tsx",
      "children": [
        "/devices/$deviceId",
        "/devices/"
      ]
    },
    "/matches": {
      "filePath": "matches.tsx"
    },
    "/scoresheet": {
      "filePath": "scoresheet.tsx",
      "children": [
        "/scoresheet/"
      ]
    },
    "/users": {
      "filePath": "users.tsx"
    },
    "/devices/$deviceId": {
      "filePath": "devices.$deviceId.tsx",
      "parent": "/devices"
    },
    "/devices/": {
      "filePath": "devices.index.tsx",
      "parent": "/devices"
    },
    "/scoresheet/": {
      "filePath": "scoresheet.index.tsx",
      "parent": "/scoresheet"
    },
    "/test/": {
      "filePath": "test/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
