interface TargetResult {
  targetResult: 'hit' | 'missed' | null;
}

interface Turn extends TargetResult {
  roundIndex: number;
  turnIndex: number;
  timestamp?: any; // Generated by Sender (target sensor), used for calculation and result display
}


type GameRounds = Turns[];

// LoRa related stuff
interface ILoRaMessage {
  type: string;
  meta: {
    orginator: string;
    intendedReceiver: string;
    timestamp: string;
  },
  payload?: JSONValue;
}
